def global_links(request):
    return {
        "nav_items" : [
        {
            "title": "The Institute",
            "link": "/institute",
            "content": [
                {"title": "About the Institute", "link": "/institute"},
                {"title": "Campus and Facilities", "link": "/institute/campus"},
                {"title": "Rules and Regulation", "link": "/institute/rules"},
                {"title": "RTI", "link": "/institute/rti"},
                {"title": "CVC", "link": "/institute/administration/vigilanceOfficer"},
                {"title": "Public Grievances", "link": "/institute/PublicGrievances"},
                {"title": "Photo Gallery", "link": "/institute/gallery"},
                {"title": "Forms to Download", "link": "/institute/forms"},
                {"title": "Contact Administration", "link": "/institute/contact"},
                {"title": "NIRF", "link": "/institute/nirf"},
                {"title": "Women Cell", "link": "/institute/womencell"},
                {"title": "ICC", "link": "/institute/icc"},
                {"title": "Spicmacay", "link": "/institute/spicmacay"},
                {"title": "IQAC", "link": "/institute/iqac"},
                {"title": "Newsletter (Pariprashna)", "link": "/institute/newsletter"},
                {"title": "Campus Connect Newsletter", "link": "/institute/campusconnect"},
                {"title": "Bulletin Ph.D Newsletter", "link": "/institute/bulletin"},
                {"title": "Networks & Systems", "link": "/netandsys"},
            ],
        },
        {
            "title": "Academics",
            "link": "/academics",
            "content": [
                {"title": "Departments", "link": "/academics/departments"},
                {"title": "Academic Office", "link": "/academics/office"},
                {"title": "Admission", "link": "/students/admission"},
                {"title": "Exam Results", "link": "/academics/results"},
                {"title": "Academic Calendar", "link": "/academics/calendar"},
                {"title": "Curriculum and Syllabi", "link": "/academics/curriculum"},
                {"title": "Institute Fee Structure", "link": "/academics/fee-structure"},
                {"title": "NEP-2020 Cell", "link": "/academics/nep"},
                {"title": "Forms to Download", "link": "/institute/forms"},
                {"title": "Rules and Regulation", "link": "/institute/rules"},
                {"title": "Convocation", "link": "/academics/convocation"},
                {"title": "NAD", "link": "/academics/nad"},
                {"title": "Scholarship", "link": "/academics/scholarship"},
                {"title": "Exam Schedule", "link": "/academics/exam"},
                {"title": "Physical Education", "link": "/physicalEducation"},
                {"title": "Emails for Contacts", "link": "/academics/emailContacts"},
                {"title": "Educational Verification Procedure", "link": "/static/pdf/Educational Verification Procedure/Procedure_for_verification2022.pdf"},
            ],
        },
        {
            "title": "Administration",
            "link": "/institute/administration"
        },
        {
            "title": "Students Welfare",
            "link": "/students",
            "content": [
                {"title": "Rules and Regulations", "link": "/students/studentrules  "},
                {"title": "Anti-ragging", "link": "/students/antiragging"},
                {"title": "Student Council", "link": "/students/council"},
                {"title": "Annual Fest", "link": "/students/annualfest"},
                {"title": "Orientation", "link": "/students/orientation"},
                {"title": "Student Clubs", "link": "/students/clubs"},
                {"title": "Student Associations", "link": "/students/student_association"},
                {"title": "Counselling Services", "link": "/students/councelling"},
                {"title": "Medical Insurance", "link": "/students/medical_insurance"},
                {"title": "NCC", "link": "/students/ncc"},
                {"title": "NSS", "link": "/students/nss"},
                {"title": "Physical Education & Sports", "link": "/physicalEducation"},
                {"title": "Forms to Download", "link": "/institute/forms"},
                {"title": "Alumni Relations", "link": "/students/aluminiRelations"},
                {"title": "Grievance Redressal", "link": "/students/Grievance Redressal"},
                {"title": "Announcements", "link": "/students/sw-announcements"},
            ], 
        },
        {
            "title": "Hostel",
            "link": "/hostel", 
            "content": [
                {"title": "Hostel Administration", "link": "/hostel/hostelAdministration"},
                {"title": "Hostel Facilities", "link": "/hostel/hostel_facilities"},
                {"title": "Rules and Regulations", "link": "/static/docs/hostel/Hostel Rules.pdf"},
                {"title": "Code of Conduct", "link": "/static/docs/hostel/Updated code of conduct - Hostel.pdf"},
                {"title": "Circular", "link": "/hostel/circular_hostel"},
                {"title": "Contact Us", "link": "/hostel/hostelRules    "},
                {"title": "Forms to Download", "link": "/institute/forms"},
            ],
        },
        {
            "title": "Faculty & Staff",
            "link": "/faculty/facultyDirectory",
            "content": [
                {"title": "Administration Head Directory", "link": "/faculty/adminDirectory"},
                {"title": "Dean Directory", "link": "/faculty/deanDirectory"},
                {"title": "HOD Directory", "link": "/faculty/hodDirectory"},
                {"title": "Faculty Directory", "link": "/faculty/facultyDirectory"},
                {"title": "Faculty On Contract Directory", "link": "/faculty/focDirectory"},
                {"title": "Officer Directory", "link": "/faculty/officerDirectory"},
                {"title": "P&D Directory", "link": "/faculty/pdDirectory"},
                {"title": "Staff Directory", "link": "/faculty/staffDirectory"},
                {"title": "Faculty Welfare Office", "link": "/faculty/faculty-welfare"},
                {"title": "Career", "link": "/faculty/career "},
                {"title": "Forms to Download", "link": "/institute/forms"},
            ]
        },
        {
            "title": "Research & Consultancy",
            "link": "/research",
            "content": [
                {"title": "Research & Consultancy Office", "link": "/research/office"},
                {"title": "IEEE", "link": "/research/IEEE"},
                {"title": "List of R&C Committees", "link": "/research/committees"},
                {"title": "Patents", "link": "/research/publications"},
                {"title": "Funded Projects", "link": "/research/fundedProjects"},
                {"title": "Journals", "link": "/research/journal"},
                {"title": "Book Chapter", "link": "/research/bookChapter"},
                {"title": "Conference", "link": "/research/conference"},
                {"title": "Consultancy Projects", "link": "/research/consultancyProjects"},
                {"title": "IPR Cell", "link": "/research/ipr"},
                {"title": "Forms to Download", "link": "/forms/research"},
                {"title": "IIC", "link": "/research/innovation"},
                {"title": "NISP", "link": "/research/nisp"},
                {"title": "Industry Consultancy", "link": "/alumni/industryConsultancy"},
                {"title": "MoU", "link": "/alumni/mou"},
                {"title": "Central Instrumentation Facility (CIF)", "link": "/CIF"},
            ]
        },
        {
            "title": "Training and Placement",
            "link": "/training_and_placement",
            "content": [
                {"title": "About", "link": "/training_and_placement"},
                {"title": "Placement Procedure", "link": "/training_and_placement/procedure"},
                {"title": "Training Programs & Activities", "link": "/training_and_placement/program"}, 
                {"title": "Infrastructure and Facilities", "link": "/training_and_placement/infrastructure"},
                {"title": "Placement Statistics", "link":  "/training_and_placement/recruitments"},
                {"title": "Testimonial", "link": "/training_and_placement/testimonial"},
                {"title": "Internship", "link": "/students/internship"},
                {"title": "Contact", "link": "/training_and_placement/contact"},
            ],
        },
    ],
    "quickLinks" : [
        {"title": "Gallery", "link": "/institute/gallery"},
        {"title": "Forms for Download", "link": "/institute/forms"},
        {"title": "People at NITPY", "link": "/faculty/facultyDirectory"},
        {"title": "NAD", "link": "/academics/nad"},
        {"title": "Women Cell", "link": "/institute/womencell"},
        {"title": "Stores and Purchase", "link": "/institute/administration/stores"},
        {"title": "ID Cards", "link": "/idcard"},
        {"title": "Alumni", "url": "https://www.nitpyalumni.com/home/index"},
        {"title": "NISP", "link": "/research/nisp"},
        {"title": "SC/ST/OBC cell", "link": "/scstobc_cell"},
        {"title": "Networks & Systems", "link": "/netandsys"},
        {"title": "List of Holidays", "url": "/static/docs/holidays/List of holidays NIT Puducherry 2025.pdf"},
        {"title": "Public Grievances", "link": "/institute/PublicGrievances"},
        {"title": "Medical Facilities", "link": "/students/medical"},
        {"title": "Physical Education", "link": "/academics/physicalEducation"},
        {"title": "List of committees", "link": "/institute/administration/committeeList"},
        {"title": "PARIPRASHNA", "link": "/institute/newsletter"},
        {"title": "Campus Connect Newsletter", "link": "/institute/campusconnect"},
        {"title": "NITPY BULLETIN", "link": "/institute/bulletin"},
        {"title": "Central Library", "link": "/library"},
        {"title": "DASA", "url": "https://dasanit.org/dasa2021/"},
        {"title": "SMDP", "url": "https://www.nitpy.ac.in/old_website/SMDPWebsite/"},
        {"title": "Guest House", "link": "/GuestHouse"},
        {"title": "Hostel Facilities", "link": "/hostel/hostel_facilities"},
        {"title": "NCC", "link": "/students/ncc"},
        {"title": "Support Center", "url": "http://172.18.5.212/"},
    ]
    }
